version: 2
updates:
  - package-ecosystem: pnpm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: webpack
        versions:
          - 5.0.0-3
