version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "compression-webpack-plugin"
      - dependency-name: "eslint"
      - dependency-name: "sass"
      - dependency-name: "sass-loader"
      - dependency-name: "stylelint"
      - dependency-name: "stylelint-config-recess-order"
