name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Docs'
    labels:
      - 'docs'
  - title: 'style'
    labels:
      - 'style'
  - title: 'refactor'
    labels:
      - 'refactor'
      - 'perf'
      - 'test'
      - 'refactor'
  - title: 'build'
    labels:
      - 'build'
      - 'ci'
  - title: 'revert'
    labels:
      - 'revert'
  - title: 'Maintenance'
    label: 'chore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
