name: oss
on:
  push:
    branches:
      - master
jobs:
  oss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          # https://github:com/marketplace/actions/tencent-cos-action:
          # https://cloud.tencent.com/document/product/436/10976#.E6.8C.87.E5.AE.9A-bucket-.E5.92.8C-region-.E7.9A.84.E5.91.BD.E4.BB.A4
          args: delete -r -f /dgiot_release/dashboardCdn/public/ && upload -r ./public/ /dgiot_release/dashboardCdn/public/
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-shanghai-fsi
