name: ci

on:
  pull_request:
    types: [opened, synchronize, edited]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: false
      - name: Pnpm script
        run: |
          pnpm config set registry https://registry.npmmirror.com
          rm -rf pnpm-lock.yaml
          pnpm install
          pnpm audit
          pnpm lint
          pnpm lint:fix
          pnpm lint:style
          pnpm build
      - uses: actions/upload-artifact@v2
        name: Upload Installer
        with:
          name: WeakAuras-Companion-PRCI-Installer
          path: dist_electron/*.exe\

  accurics:
    runs-on: ubuntu-latest
    name: accurics-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: accurics-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://app.accurics.com/v1/api/terrascan
          webhook_token: a20de3ab-f00e-4e1a-a37f-dbceafe4150e
